version: '3.8'
services:
  fastapi-backend:
    build: .
    ports:
      - 8000:80
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/mydb
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - EMAIL_ADDRESS=assolaange777@gmail.com
      - EMAIL_PASSWORD=w p j v t j h r g s p d c n r k
    container_name: fastapi-backend
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    container_name: postgres_db
    restart: unless-stopped

volumes:
  postgres_data: